# Development Dockerfile
FROM node:20-alpine

RUN apk add --no-cache openssl

WORKDIR /app

COPY package.json package-lock.json* ./
COPY prisma ./prisma
RUN npm install
RUN npx prisma generate

COPY . .

EXPOSE 3000
ENV NODE_ENV=development
ENV PORT=3000

CMD ["npm", "run", "dev"]
